elasticsearch:
  ip: 82.157.125.33
  port: 9200
  scheme: http

server:
  port: 87

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-search

# feign调用超时时间配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000